isoos/postgresql-dart

CHANGELOG.md
README.md
pubspec.yaml

Let me know if you would like me to change or add anything.

[Streaming Replication Final] Bump version, add change logs and update readme

---

dev/README.md
test/connection_test.dart
test/decode_test.dart
test/docker.dart
test/encoding_test.dart
test/json_test.dart
test/logical_replication_test.dart
test/map_return_test.dart
test/notification_test.dart
test/pg_configs/pg_hba.conf
test/pg_configs/postgresql.conf
test/query_reuse_test.dart
test/query_test.dart
test/timeout_test.dart
test/transaction_test.dart

Made fixes to the tests so they can run locally. 
- Make SSL work by using certs that available in the Debian version of the postgres image
- Added `usePostgresDocker` to each test file so they can be tested individually. 
- Since most tests depends on the same connection & container, it's only possible to run all tests with `--concurrency=1`. 
- Created `darttrust` user which was used by old tests (also `replication` user for replication tests`)
- Added custom configs for `pg_hba.conf` and moved `configurations` list into `postgresql.conf` 
- Added a dev folder
- currently it only contains a `README.md` with instructions to run tests locally. 
This is the first step towards making all tests work on the CI.

Update setup so tests can run locally

---

lib/src/v3/connection.dart
test/v3_test.dart

For queries, surfacing errors that came from an error message sent by postgres was broken:
1. A missing await in `execute()` resulted in the exception being considered unhandled.
2. I think there is no point in surfacing the error in the stream and both completers for the schema and the amount of affected rows. It is unrealistic that one would await all three of them concurrently, and this reports additional unhandled errors otherwise. Making the stream emit the error should be enough, this is also caught by the `execute` wrapper.

V3: Fix reporting errors through error message

---

CHANGELOG.md
lib/src/binary_codec.dart
lib/src/query.dart
lib/src/substituter.dart
lib/src/v3/types.dart
pubspec.yaml
test/decode_test.dart
test/encoding_test.dart
test/query_test.dart

For reference: https://github.com/schultek/stormberry/issues/50

Add support for int8 array

---

analysis_options.yaml
lib/src/binary_codec.dart
test/docker.dart

The author seems to prefer final in other cases, so figured this one would be welcome as well.

chore: add prefer_final_in_for_each

---

lib/src/substituter.dart

I'm not 100% confident the existing tokenizer is correct, but I can at least read it better now. :)
This should be zero functional change, just refactoring to use helper methods with short names.
I could probably have even removed the explicit passing of "iterator.current" but that can be
a later change.

refactor: improve readability of substitute tokenizer

---

analysis_options.yaml
lib/src/types.dart

This isn't a big deal, just going through lints as a way of learning the codebase.

fix: add noop_primitive_operations and fix the one case it caught

---

analysis_options.yaml
lib/src/server_messages.dart
lib/src/text_codec.dart
test/connection_test.dart
test/map_return_test.dart
test/server_messages_test.dart

Added this lint since it caught at least one real bug. Also added a test for the bug.

fix: Fix errors found by avoid_dynamic_calls

---

lib/src/v3/variable_tokenizer.dart
test/variable_tokenizer_test.dart

Also fixes `V3=1` mode for `encoding_test.dart`.

v3 sql parser fix: accept :_varchar(10) as type identifier.

---

lib/postgres_v3_experimental.dart
lib/src/v2_v3_delegate.dart
lib/src/v3/connection.dart
test/connection_test.dart
test/docker.dart
test/map_return_test.dart
test/notification_test.dart
test/v3_test.dart

I've started running the test files alphabetically. With this PR, tests from `connection_test.dart` to `notification_test.dart` should run through the v3 delegate.

Make more tests work through delegate

---

test/transaction_test.dart

exception inside transaction test for v3 implementation

---

lib/postgres.dart
lib/src/pool/pool_api.dart
lib/src/pool/pool_impl.dart
test/pool_test.dart

The idea here is that a pool may select endpoints on data locality or on average latency to endpoints. Not every detail is polished, please comment!

Pool API proposal: EndpointSelector, Locality and extra parameters.

---

CHANGELOG.md
lib/src/binary_codec.dart
lib/src/types.dart
test/decode_test.dart
test/encoding_test.dart

Interval type instead of Duration.

---

lib/src/binary_codec.dart

Reduce type constraint on jsonbArray encoding

---

lib/src/messages/logical_replication_messages.dart

- Removing `typeName`. There will be a way to lookup the Type by oid, and their toString() should provide the debug information.
- `TupleData` gets a non-parsing default constructor, parse is a factory constructor (and private to the file).

Consistency refactor in logical replication messages.

---

CHANGELOG.md
lib/postgres.dart
lib/src/pool/pool_api.dart
lib/src/pool/pool_impl.dart
lib/src/v3/connection.dart
test/transaction_test.dart

Support TxSession.rollback() in Session.runTx().

---

CHANGELOG.md
lib/src/types.dart
lib/src/types/generic_type.dart
lib/src/types/type_registry.dart
lib/src/v2/substituter.dart
test/encoding_test.dart
test/v3_test.dart

Handling serial4/serial8 type names.

---

test/encoding_test.dart

Refactor encoding test + partial verification of #22

---

CHANGELOG.md
lib/src/v3/connection.dart
pubspec.yaml

Fix SSL connection handler.

---

lib/src/types/geo_types.dart
test/encoding_test.dart

Now `Box` stores its coordinates in exactly the same way as Postgres

fixed box coordinate reordering

---

CHANGELOG.md
lib/src/types.dart
lib/src/types/binary_codec.dart
lib/src/types/type_registry.dart
test/encoding_test.dart

I think I will take few weeks off adding new types. So you can release the new version if you want.

Added array types: time, date, uuid

---

CHANGELOG.md
lib/postgres.dart
lib/src/v3/connection.dart
test/decode_test.dart

- https://github.com/isoos/postgresql-dart/issues/322
- alternative to #323

Row-based isSqlNull()

---

CHANGELOG.md
lib/src/types/type_codec.dart
lib/src/v3/connection.dart
lib/src/v3/relation_tracker.dart

Minimal RelationTracker (tracking RelationMessage) with further extensibility for oid caching.

---

lib/src/types/type_codec.dart
lib/src/types/type_registry.dart

Note: this would cause way too many breaking changes, postponing them for now.

Revert asynchronous encode/decode method signatures (for now).

---

test/timeout_test.dart

- The first test won't make any sense if we get to implement `statement_timeout`.
- The others are clarification/cleanup.

Reviewed timeout tests.

---

CHANGELOG.md
lib/src/messages/server_messages.dart
lib/src/v3/protocol.dart
pubspec.yaml
test/unexpected_protocol_bytes_test.dart

Fix: prevent hanging state by forwarding protocol-level parsing errors into the message stream.

---

CHANGELOG.md
lib/src/messages/client_messages.dart
lib/src/messages/server_messages.dart
lib/src/v3/connection.dart
pubspec.yaml
test/v3_test.dart

Explicit closing of prepared statement portals in transactions to release table locks.
