CHANGELOG.md
lib/src/binary_codec.dart
lib/src/query.dart
lib/src/substituter.dart
lib/src/types.dart
test/decode_test.dart

Closes https://github.com/stablekernel/postgresql-dart/issues/50,
closes https://github.com/stablekernel/postgresql-dart/issues/108,
closes https://github.com/stablekernel/postgresql-dart/issues/112,
closes https://github.com/stablekernel/postgresql-dart/issues/162,
Contributes to https://github.com/stablekernel/postgresql-dart/issues/164
Encoder may follows, if I've time.
At least I wanted to give a decoding option to the users who need it.
I decided to use String as exact representation of BigDecimal. An alternative would be to use [decimal package](https://pub.dev/packages/decimal) , but I don't know if its a good idea, to use third party package as datatype. If wanted the users can use the package and convert the string themselves with the …

Decoder for numeric / decimal SQL Data type

---

CHANGELOG.md
lib/src/binary_codec.dart
test/decode_test.dart
test/encoding_test.dart

- Closes https://github.com/stablekernel/postgresql-dart/issues/164
- Binary Encoder for numeric / decimal SQL Data Type
- Fix decoding numeric values with trailing or leading zeros
- More tests
It seems that the implementation is quite heavy, but when I looked into other repositories, they also have a bulk of code:
- BigDecimal Implementation of [a14n](https://github.com/a14n/dart-rational/blob/a93551360c2882cb5a96118d0c4653847b30ad8f/lib/rational.dart#L62), which cannot be applied 1:1, as Postgres Numeric uses another binary format than BigDecimal.
- BigDecimal Implementation of [Java](https://github.com/frohoff/jdk8u-dev-jdk/blob/da0da73ab82ed714dc5be94acd2f0d00fbdfe2e9/src/share/classes/java/math/BigDecimal.java#L409): Same applies to Java.
- You may find another lib which implements …

Binary encoder for numeric datatype

---

CHANGELOG.md
lib/src/binary_codec.dart
lib/src/query.dart
lib/src/substituter.dart
lib/src/types.dart
pubspec.yaml
test/encoding_test.dart

Very good lib!
I added support for interval type to make it better, I hope it helps others.
Interval is represented as Duration in dart.

add support for interval

---

CHANGELOG.md
lib/src/connection.dart
pubspec.yaml

imho allowReuse should either be a non-nullable value or the default value should be used as a fallback when accessed.
otherwise callers can pass in `allowReuse: null` and cause a crash. 😳

update allowReuse nullability

---

CHANGELOG.md
lib/src/text_codec.dart
pubspec.yaml
test/encoding_test.dart
test/json_test.dart

I tried to bind a json value but couldn't get it to work. After further inspection it looks like json only works for `query` but not for `execute`.
Because of some reason `query` uses native binding, while `execute` uses `sendSimple`
https://github.com/isoos/postgresql-dart/blob/1d74c21fa160859cbb1889f945c22f39f168d4d1/lib/src/connection_fsm.dart#L198-L201
I don't understand at all why there is a difference? Why use `sendSimple` for `execute`?
This PR is only to reproduce the bug. Please advise how to fix it? Does it make sense to try to support json in `sendSimple` or should everything use `sendExtended`?
the error message is:
```
PostgreSQLSeverity.error 42601: syntax error at or near "{" 
```
(I assume the CI should show that as well)

fix sending json with execute

---

pubspec.yaml
test/docker.dart
test/error_handling_test.dart

@isoos Here is a basic test case which reproduces #13 . I've included the docker_process package, so it will run a local postgres container.

Missing stacktrace basic reproduction test

---

lib/src/connection.dart
lib/src/query.dart
lib/src/transaction_proxy.dart
test/error_handling_test.dart

@isoos Hello! I've come up with a solution for the stacktrace issue.
Since a queue is used to resolve the queries, we cannot simply include the `StackTrace` at the location of `Completer.completeError`, so when creating the `Query` object, the `StackTrace` at that time is attached. That way, when the error happens, we can use that one instead.
I don't know if there is a better way to do this kind of `StackTrace` handling, but with this (maybe naive) solution we get the exact line that caused the error.

Include original stacktrace when query fails

---

CHANGELOG.md
lib/src/auth/auth.dart
lib/src/auth/clearText_authenticator.dart
lib/src/auth/clear_text_authenticator.dart
lib/src/connection.dart
lib/src/connection_fsm.dart
pubspec.yaml

Adds the option for clear text password authentication.
Fixes connections to Azure Database for PostgreSQL.
I created a new boolean parameter at the time of creating the connection called allowClearTextPassword default to false to enable this kind of authentication for the connection.
According to https://www.postgresql.org/docs/11/protocol-flow.html#id-1.10.5.7.3 flow, this patch just returns the password to the server when requested a clear text password after a connection attempt.
For the structure of the message I didn't quite got the grasp of the byte formatting, but replicated the structure used for md5 as it follows a similar message flow. Need review on this to guarantee it is working. Local testing showed no problem.
TODO 1: I could not come up with tests, as there should be a …

Clear text conn type

---

CHANGELOG.md
lib/src/binary_codec.dart
lib/src/query.dart
lib/src/substituter.dart
lib/src/types.dart
test/decode_test.dart
test/encoding_test.dart
test/query_test.dart

Hi there,
Nice library!
I am utilizing varchar arrays in PostgreSQL in various tables and I needed a way to have such support in Dart projects as well.
I believe there are many people that might also need this feature enabled in your driver, e.g. storing & accessing lists of smaller-sized strings, like the following samples:
`tags varchar(50)[]`  or `tags _varchar(50)`
`emojis _varchar(4)` etc.
Hence I thought to add it...

Added support for varchar array fields

---

CHANGELOG.md
lib/src/binary_codec.dart
lib/src/query.dart
lib/src/substituter.dart
lib/src/text_codec.dart
lib/src/types.dart
pubspec.yaml
test/decode_test.dart
test/encoding_test.dart
test/query_test.dart

Added support for boolean arrays in binary and text form.

Added support for boolean array fields

---

CHANGELOG.md
lib/src/connection_fsm.dart
pubspec.yaml
test/transaction_test.dart

The connection FSM expected a `_TransactionProxy` when receiving transaction messages, but it's actually safe to just expect a general execution context implementation.
Closes #43.

Allow manual transaction management

---

pubspec.yaml

Closes: #54 
I think it's better to have this on its own PR. Though, if this is accepted, I'm not sure if bumping the version should occur here or in a separate PR after all PRs are completed. 
By the way, I cannot add more PRs for now as the rest of the changes requires the functionality of this PR as well as the other three that were submitted before this one. 
I was thinking to add the version and CHANGELOG in a separate PR so it's easier to merge everything. Otherwise I'd have to rebase each PR after the other.

[Streaming Replication 4th] Raise the min sdk version to support enhanced enums

---

lib/src/server_messages.dart

When using non-standard command such as 'IDENTIFY_SYSTEM', the parsing had an issue where it'll parse `SYSTEM` as the integer. A new reliable regex was added to parse the affected rows correctly if there's any.

[Streaming Replication - 2nd] Fix affected rows parsing in CommandCompleteMessage

---

lib/src/time_converters.dart
lib/src/types.dart
test/time_converter_test.dart
test/types_test.dart

- Adds Log Sequence Number type -- used widely by the Streaming Replication Messages 
- Adds conversion form and to microseconds since 2000-01-01 (the baseline time used by PostgreSQL in replication messages).

[Streaming Replication - 3rd] Add LSN type and time conversion to and from ms-since-Y2K

---

.gitignore
lib/src/connection.dart
lib/src/connection_fsm.dart
lib/src/execution_context.dart
lib/src/query.dart

This PR adds functionality that's necessary for Streaming Replication.
The following will be the additions to `PostgreSQLConnection`:
- `querySimple` method
-  Similar to `execute`, but it'll return whatever data the server gives. 
- This is necessary since in streaming replication mode, the extended query protocol cannot be used. On the other hand, `execute` does not return any data. `querySimple` was introduced to avoid breaking the existing API and to allow querying the database in Replication Mode which is necessary (i.e. executing `IDENTIFY_SYSTEM;` and retrieving the system info data) 
- `addMessage` method
- I assumed since the socket is already publicly exposed, there's no harm of adding this method. 
- `Stream<ServerMessage> messages` 
- Since `socket` is a single listener …

[Streaming Replication - 1st] Introduce new methods and getter to  PostgreSQLConnection

---

lib/src/client_messages.dart
lib/src/connection.dart
lib/src/connection_fsm.dart
lib/src/constants.dart
lib/src/replication.dart
test/connection_test.dart

This change simply allows running `PostgreSQLConnection` in replication mode in the following manner:
```dart
final conn = PostgreSQLConnection(
'localhost',
5432,
'postgres',
username: 'postgres',
password: 'postgres',
replicationMode: ReplicationMode.logical,
);
```
Tests were added which shows the use of `useSimpleQueryProtocol` (turning that off will make the test fail)
----

[Streaming Replication 5th] add connection configuration for Streaming Replication Protocol

---

lib/messages.dart
lib/src/client_messages.dart
lib/src/logical_replication_messages.dart
lib/src/server_messages.dart
lib/src/shared_messages.dart

This change adds new messages types for both client and server. These messages are from the following sources:
- [Protocol Message Formats](https://www.postgresql.org/docs/current/protocol-message-formats.html) -- shared messages (e.g. CopyData and CopyDone). 
- [Streaming Replication Protocol](https://www.postgresql.org/docs/current/protocol-replication.html) -- server/client messages for replication -- i.e.  XLogData (server), PrimaryKeepAlive (server), Standby Status Update (client), and Hot Standby feedback message (client). 
- [Logical Replication Message Formats](https://www.postgresql.org/docs/current/protocol-logicalrep-message-formats.html) -- all of them were added to a new file. 
Next PR (or max two) will contain the code handling these messages when replication mode is used.

[Streaming Replication 6th] Add new message types for replication

---

lib/postgres.dart
lib/src/logical_replication_messages.dart
lib/src/message_window.dart
lib/src/server_messages.dart
test/framer_test.dart
test/logical_replication_test.dart

This PR includes the following changes/additions:
- Modify MessageFramer to handle replication messages with added tests
- Added  a logical replication test but for now it cannot work on the CI (but can be ran locally)
- the test itself has comments on the reason. 
I'll submit a final PR after this to update changelogs, version, and readme.

[Streaming Replication 7th] Replication Mode Messages Handling

---

pubspec.yaml
test/docker.dart
test/logical_replication_test.dart

- Fixed a string concatenation issue that made the test fail before. 
-  updated `docker_process` in `dev_dependencies`
- Simplified the test by adding configurations directly to `usePostgresContainer`. 
----
On another note, I tried to make the logical replication test work on the CI in my fork but with no success. I could not find a way to pass image arguments to the container in the current setup of `dart.yaml`. I think a custom container would be needed but maybe that can be done another time.
For reference, mounting a volume with the current setup also wasn't straight forward. Here's the workaround for future reference: 
```yaml
services:
postgres:
.....
volumes:
- ${{ github.workspace }}/test/custom_config/postgresql.conf:/etc/postgresql/postgresql.conf
.....
steps:
- name: Change …
```

Fix an issue with logical replication test and simplify the test

---

CHANGELOG.md
lib/src/connection.dart
pubspec.yaml

`substitutionValues` was ignored for `useSimpleQueryProtocol` -- my bad.

Add substitutionValues for useSimpleQueryProtocol

---

test/non_ascii_connection_strings_test.dart

I was taking a look at https://github.com/isoos/postgresql-dart/issues/38 but I could not reproduce the issue (actually I remember facing issues with `@` symbol a while back as well but I could not reproduce that either).
Anyway, I've already added tests for passwords using non-ASCII characters for the three supported auth methods by the package -- namely:
- clear password 
- md5
- scram-sha-256
All of them pass (won't work on the CI though as each test needs its own `pg_hba.conf` to be mounted).
~They might be useful to keep if you think so.~ -- I believe they are necessary based on the next comment.

add non-ascii connection string tests

---

.github/workflows/dart.yml
test/connection_test.dart
test/docker.dart
test/logical_replication_test.dart
test/non_ascii_connection_strings_test.dart
test/notification_test.dart

This should allow running all tests (34 tests that were not running on Github before the change). 
I avoided using tags because it'll just complicate the process for no added benefits. I think with concurrency of "1", the tests will run for extra 30~60 seconds than it was before; on the other hand, the setup is straightforward in both the test files and the workflow file.  
p.s. I didn't know that ubuntu comes with docker installed so the change was easier than I thought.

Update GitHub actions to run all tests 

---

CHANGELOG.md
lib/src/connection_fsm.dart
pubspec.yaml
test/connection_test.dart

Fixes #65
`_authenticator.onMessage(message);` was throwing `Null check operator used on a null value` exception but it was not propagated properly to the completer in the `open()` method.

No password non trusted users

---

lib/src/v3/connection.dart
test/v3_test.dart

For DDL statements, postgres will not respond with a `RowDescriptionMessage`, which means that the completer for the `PgSchema` in a v3 query stream is never completed.
This is kind of counter-intuitive, and it breaks `PgSession.execute` which awaits the schema. To solve this problem, I've made the completers complete with default values if we didn't get anything back from postgres.

V3: Fix deadlock for statements without a schema

---

CHANGELOG.md

I think the current state can be released as it is (I left the version number at 2.6.0 since that one hasn't been published yet).
I'm not sure if we need a preview release number since the main libraries (`package:postgres/postgres.dart` and `messages.dart`) continue to be stable. Only the new library is experimental, which is mentioned in the changelog.

Add changelog for v3 API

---

test/logical_replication_test.dart

Fixes https://github.com/isoos/postgresql-dart/issues/99
Table creation in postgres 15+ is disallowed by default in the public schema.  So either we would need to give
the dart_test user explicit permission to modify the public schema, or (what I chose here) we just use a
separate schema for this test:
https://www.cybertec-postgresql.com/en/error-permission-denied-schema-public/

Fix logical_replication_test on postgres 15+

---

lib/postgres_v3_experimental.dart
lib/src/v3/connection.dart
pubspec.yaml
test/v3_test.dart

This implements the `run` and `runTx` methods in the v3 draft.
I think much of the confusion related to exceptions in the old API comes from the fact that not awaiting statements was supported. Given that this is rarely a good idea, we can just forbid this in the v3 API and always rethrow the original exception.
To implement this, I've lifted the `_operationLock` from the connection class into a shared session class. This allows transactions to use their own `_operationLock` while keeping the one from the connection locked the entire time.

Implement transactions in v3 API

---

lib/postgres_v3_experimental.dart
lib/src/binary_codec.dart
lib/src/query.dart
lib/src/substituter.dart
lib/src/v3/connection.dart
lib/src/v3/types.dart
test/encoding_test.dart
test/interpolation_test.dart
test/v3_test.dart

In the v3 API, we're using the simple query protocol when there are no variables in the query. Unfortunately, rows are always returned in the textual format with that protocol. As the binary decoder is more efficient and supports more types, we'd like to use that one instead.
For users that know they won't need any rows, I've added the `schemaOnly` parameter to `execute`. When enabled and there are no parameters, we can still use the simple query protocol as an optimization.
This fixes https://github.com/isoos/postgresql-dart/issues/101.

Improve row decoding in v3 API

---

lib/postgres_v3_experimental.dart
lib/src/connection.dart
lib/src/query.dart
lib/src/substituter.dart
lib/src/v3/query_description.dart
lib/src/v3/types.dart
lib/src/v3/variable_tokenizer.dart
pubspec.yaml
test/v3_test.dart
test/variable_tokenizer_test.dart

This:
- Adds the type name used for the old substitution logic into the `PgDataType` definition, avoiding that being duplicated.
- Implements `PgSql.map` by lexing the postgres statement.
I've tried to keep the new interface close to the old one, but I think there are some opportunities to improve it that are breaking:
- When a variable is declared with `SELECT @foo`, the name in the map is just `foo` instead of `@foo`. I think this might make variables easier to bind when using custom substitution chars and generally makes the map more pleasant to look at.
- Only variables that are actual variables are considered. When a substitution character appears in a string literal, an identifier or a comment, it is ignored.

Query substitution in V3 API

---

lib/postgres_v3_experimental.dart
lib/src/v3/connection.dart
lib/src/v3/pool.dart
test/pool_test.dart

This PR removes some options and parameters that aren't implemented yet (like timeouts). Adding them back won't be breaking, so it's something we can implement later. It seems like none of these features (except timeouts) are supported by the v2 API either. And since timeouts can't be implemented in a clever way (there's no way in the protocol to cancel existing queries, for instance), users should probably just timeout the future themselves instead?
Removing these options made it somewhat easier to implement a simple pool that creates connections when they are first used and is able to re-use them.

Pool implementation for the v3 API

---

lib/src/v3/types.dart
test/types_test.dart

Oring hashCode values is an old style which is wrong in the case of swapped values.  Fixed by using Object.hash.
Also marked PgPoint immutable, since that's the modern style.

fix: PgPoint.hashCode is wrong.

---

analysis_options.yaml

Both iterable_contains_unrelated_type and list_remove_unrelated_type were replaced by collection_methods_unrelated_type.

chore: Remove deprecated lints.

---

example/v3/example.dart
lib/postgres_v3_experimental.dart
lib/src/v3/pool.dart

I believe there's no reason to force the user to add `null` as a parameter as it was shown in the example:
- before
```dart
final result = await statement.run(null);
```
- after
```dart
final result = await statement.run();
```
_let me know if I need to add a changelog entry or if you prefer to publish this with other changes later_

feat: let `PgStatement.run` parameters be optional positional (v3)

---

analysis_options.yaml
lib/src/auth/clear_text_authenticator.dart
lib/src/auth/md5_authenticator.dart
lib/src/auth/sasl_authenticator.dart
test/encoding_test.dart
test/interpolation_test.dart
test/query_test.dart

The super parameters change is an obvious win, the raw strings change is debatable, but I think it still makes at least the short strings more readable.

chore: add use_raw_strings and use_super_parameters

---

analysis_options.yaml
lib/src/auth/auth.dart
lib/src/binary_codec.dart
lib/src/logical_replication_messages.dart
lib/src/text_codec.dart

Modern dart (especially with sealed) makes it easy to avoid default in most cases, so adding the lint and removing all but one.
I think this may have unearthed a bug in binary_codec, but I wasn't sure of the fix so just left a TODO for now.

fix: add no_default_cases lint and remove unnecessary defaults

---

lib/postgres_v3_experimental.dart
lib/src/v3/connection.dart

I am just splitting #121 (draft) in smaller PRs to push the easy pieces out of the way until #118 (simple query execution) is decided upon.

feat: add replication mode flag (v3)

---

analysis_options.yaml
example/v3/example.dart
lib/src/binary_codec.dart
lib/src/exceptions.dart
lib/src/query.dart
lib/src/text_codec.dart
lib/src/v3/types.dart
test/map_return_test.dart

Adding:
- unnecessary_null_checks
- unnecessary_parenthesis
- unnecessary_raw_strings Each of these found real cases where fixing with the lint improved readability (one could argue about the raw strings).

chore: add uneccessary_* lints

---

lib/src/binary_codec.dart
lib/src/query.dart
lib/src/v3/types.dart
test/decode_test.dart
test/encoding_test.dart
test/v3_test.dart

`PgDataType.numeric` is instantiated with the `List<int>` type parameter. I think this is wrong, the parameter must have been taken from the comment by mistake.
Looking at the implementation for `numeric` in the binary encoder and decoder, it seems like we support encoding these values from ints, doubles and strings. But we're always decoding them as strings. Since these types share no common interface, the type need to be declared as `Object` to avoid the `as T` in the decoder failing.
I've also added a constructor directly taking a type to avoid the double lookup from and to oids.

Fix decoding numeric values

---

lib/src/binary_codec.dart

The Dart SDK, or at least the VM implementation, contains an optimized encoding and decoding pipeline for json to utf8 bytes. By using that instead of chaining the encoders/decoders manually, we can avoid the intermediate strings and make these operations slightly faster.

Optimize json encoding and decoding

---

lib/src/binary_codec.dart
lib/src/buffer.dart
lib/src/client_messages.dart
lib/src/query.dart
lib/src/text_codec.dart
lib/src/v3/connection.dart
lib/src/v3/types.dart
test/decode_test.dart
test/encoding_test.dart

- Instead of that caching we should have fewer places with `switch` statements.
- Makes the encoding explicit in more convert methods.

Remove codec properties from PgDataType.

---

lib/postgres_v3_experimental.dart
lib/src/text_codec.dart
lib/src/v3/connection.dart
lib/src/v3/pool.dart
test/v3_test.dart

The Simple Query Protocol is the only protocol that can be used when the connection is in Replication Mode in order to query system information such as `IDENTIFY_SYSTEM;` query.
Currently, the only way to use the Simple Protocol is to set `ignoreRows`  to `true` but this will return no result and there's no way around it. 
While taking @simolus3 comment from PR #102 into consideration, I added an option to explicit use the Simple Query Protocol. In addition, it is used when there are no parameters and `ignoreRows` is set to true.

feat: allow explicit use of Simple Query Protocol (v3)

---

lib/src/v3/connection.dart
test/v3_logical_replication_test.dart

- Added logical replication tests for v3 
- Handle `CopyBothResponseMessage` case in message handler

feat: Add Logical Replication Tests for v3

---

lib/src/text_codec.dart

Partly fixes #125
- For `PgDataType.voidType`, return `null`. 
- For any unimplemented type, return whatever was decoded as text 
-  I believe it's better to return something than throw an exception 
----
Context:
I was running this query and I received the following error:
```
--> data ReadyForQueryMessage(state = I)
<-- data Instance of 'QueryMessage'
sending Qnselect pg_drop_replication_slot('a_test_slot') from pg_replication_slots where slot_name = 'a_test_slot';
--> data Instance of 'RowDescriptionMessage'
--> data Data Row Message: [[]]
Unhandled exception:
UnimplementedError: Text decoding for PgDataType.voidType
```

fix: handle PgDataType.voidType

---

test/error_handling_test.dart

This print statement shows "an error" message in the test logs which was confusing
_btw, thanks for #145 -- tests now run much faster locally_

chore: remove unncessary print in tests

---

lib/postgres_v3_experimental.dart
lib/src/client_messages.dart
lib/src/v3/connection.dart
lib/src/v3/query_description.dart
test/docker.dart
test/pool_test.dart
test/transaction_test.dart
test/v3_close_test.dart
test/v3_logical_replication_test.dart
test/v3_test.dart

Following the suggestions from https://github.com/isoos/postgresql-dart/issues/105#issuecomment-1676364521, this migrates `test/transaction_test.dart` to use the v3 API.
To make the migration easier, and to keep more compatibility with the v2 API, I've changed the v3 implementation to substitute named variables by default. The few users who'll need full control over SQL in the v3 API can use the `PgSql` wrapper.

Migrate transaction tests to v3

---

lib/src/v2_v3_delegate.dart
test/docker.dart

Use the following to trigger v3 as delegate:
```
V3=1 dart test test/decode_test.dart
```

Use v3 as delegate behind v2 interface.

---

lib/src/binary_codec.dart
lib/src/query.dart
lib/src/v3/connection.dart
lib/src/v3/query_description.dart
lib/src/v3/types.dart
test/interpolation_test.dart
test/variable_tokenizer_test.dart

- Unblocks more queries in `query_tests.dart`.
- Using the insight from @simolus3, and using the encoding of `ParameterValue`.

Handle unspecified types in queries.

---

test/connection_test.dart
test/docker.dart
test/map_return_test.dart
test/query_test.dart

- cleared `query_test.dart`, now it is v3-compatible
- moved skippedOnV3 method to `server`, so that we could (in a follow-up PR) run the same tests twice with v2 and v3 mode

Move skippedOnV3 to the server instance.

---

lib/src/transaction_proxy.dart
lib/src/v2_v3_delegate.dart
test/v2_transaction_test.dart

We could add `cancelTransaction` to a new `PgTxSession extends PgSession` interface, but that may happen at a later time. I've started with that implementation, but then `runTx` may not return `<R>` only either untyped object, or a wrapper or `<R?>`...

Implement cancelTransaction + skips for v2_transaction_test.dart

---

example/v3/example.dart
lib/postgres_v3_experimental.dart
lib/src/v2_v3_delegate.dart
lib/src/v3/connection.dart
lib/src/v3/pool.dart
test/docker.dart

Note: `PgStatement.run` has a breaking change in method signature. to be reviewed with the rest of v3 soon.

Implement query timeout + enable both v2 and v3 adapter tests

---

lib/postgres.dart
lib/src/binary_codec.dart
lib/src/execution_context.dart
lib/src/query.dart
lib/src/substituter.dart
lib/src/types.dart
test/decode_test.dart
test/encoding_test.dart
test/interpolation_test.dart
test/query_reuse_test.dart
test/query_test.dart

type alias is kept in top-level postgres.dart library.

Cleanup of PostgreSQLDataType (using PgDataType instead).

---

LICENSE

There is no change in the license terms, only fixing phrases that confuse pana / dart.dev.

Fix LICENSE to be recognizable by pub.dev.

---

lib/postgres.dart
lib/src/exceptions.dart
lib/src/v3/connection.dart
test/connection_test.dart
test/docker.dart
test/non_ascii_connection_strings_test.dart
test/pool_test.dart
test/v3_close_test.dart
test/v3_logical_replication_test.dart
test/v3_test.dart

- This follows the other Postgres client libraries better.
- /cc @simolus3 to have a second pair of eyes on the `connection.dart` changes: it triggers SSL connection unless `sslMode = SslMode.disable`, most of it is indent changes + how the `adaptedStream` is initialized.

SslMode instead of requireSsl and allowCleartextPassword.

---

lib/messages.dart
lib/src/client_messages.dart

Also adding the buffer writer in the exported library.

Remove @internal annotation from ClientMessage methods.

---

CHANGELOG.md
lib/src/binary_codec.dart
lib/src/text_codec.dart
lib/src/types.dart
lib/src/v2/query.dart
lib/src/v3/connection.dart
test/decode_test.dart
test/encoding_test.dart

Also:
- explicit list of the types not handled yet in text decoder
- removed unusable type cast in both the binary and the text decoder

Return explicit TypedBytes data class when the package is not able to decode the input bytes.

---

lib/postgres.dart
lib/src/v3/query_description.dart
lib/src/v3/variable_tokenizer.dart
test/variable_tokenizer_test.dart

In addition to `Sql.named`, this adds `Sql.indexed` where variables are given numbers instead of names.
This should close https://github.com/isoos/postgresql-dart/issues/93 (cc @insinfo, could you take a look if this is what you had in mind?).

Desugar positional variables

---

.github/workflows/dart.yml
example/example.dart

A working example is helpful for users getting started with this package, so that they can take code known to work as a starting point.
This adds documentation comments to the example explaining how to run it. It also fixes the statements to set everything up, meaning that the example can now be run. To ensure future changes don't break the example, I've added a CI step running it.

Ensure example works

---

lib/src/types.dart
lib/src/types/binary_codec.dart
lib/src/types/generic_type.dart
lib/src/v2/query.dart
lib/src/v3/connection.dart
test/decode_test.dart
test/encoding_test.dart

This is also important for the use case where we have separate type classes.

DecodeInput.typeRegistry

---

CHANGELOG.md
lib/src/types.dart
lib/src/types/binary_codec.dart
lib/src/types/text_codec.dart
lib/src/types/type_registry.dart

Originally I thought that `TypedBytes` may be useful for other use cases, but I don't see it happen, and the extra format + the encoding info is also useful if somebody needs to process it.

Rename TypedBytes -> UndecodedBytes.

---

CHANGELOG.md
lib/src/pool/pool_impl.dart
test/pool_test.dart

In some cases the connection gets closed after a query is executed without throwing an error. This patch checks to see if the connection has been closed and disposes of it.
steps to replicate:
```dart
final conn = Pool.withEndpoints(....);
await conn.execute('-- test'); // this doesn't throw but it causes the connection to close
await conn.execute('select true'); // this throws because the pool picks up the previously closed connection. a PgException(Severity.error Connection is closing down) error is thrown. 
```

Dispose closed pool connections

---

CHANGELOG.md
lib/postgres.dart
lib/src/pool/pool_api.dart
pubspec.yaml

or else prevents me from making const repository classes

added const for settings classes

---

lib/src/types.dart
lib/src/types/binary_codec.dart
lib/src/types/text_codec.dart
lib/src/types/type_registry.dart
test/encoding_test.dart

As apparently `char` (without any size in parenthesis) is a special data type in postgres that is not intended for external use.

rename Type.char -> character

---

CHANGELOG.md
lib/src/v3/connection.dart
lib/src/v3/protocol.dart
pubspec.yaml
test/docker.dart
test/v3_test.dart

When postgres wants to shut a connection down, it usually sends a terminate message first. But if the server gets killed or the TCP socket is dropped due to connectivity changes, we should still detect that and wind the connection down gracefully (more or less, without connectivity).
With this PR, the connection will react to the stream closing by reporting pending operations as failed. Further, it will complete the `closed` future, allowing clients to reliably detect closing connections.
The second commit closes https://github.com/isoos/postgresql-dart/issues/279.

React to connection losses

---

CHANGELOG.md
lib/postgres.dart
lib/src/messages/server_messages.dart
lib/src/types.dart
lib/src/types/binary_codec.dart
lib/src/types/geo_types.dart
lib/src/types/range_types.dart
lib/src/types/text_codec.dart
lib/src/types/type_registry.dart
pubspec.yaml
test/encoding_test.dart

I added some builtin types as discussed in issue #293.
This is the first time I contribute to a project on Github, so I'm more than happy to fix any issues you might see with pull request.
Once is merged, I would add `numrange`, but I wanted to ask if it wouldn't be better to change the current `numeric` type from `GenericType<Object>(TypeOid.numeric)` that accepts `int`, `double` and `String` to `GenericType<Decimal>(TypeOid.numeric)` using the decimal library (https://pub.dev/packages/decimal).

Add builtin time, geometric and most range types

---

lib/src/v3/variable_tokenizer.dart
test/variable_tokenizer_test.dart

I would like to use named parameters like this: `:param`. (mainly because it works so well in jetbrains IDEs).
It works with simple queries:
```dart
Sql.named('select * from device where id=:id', substitution: ':')
```
The problem is the sql parser chokes when we also use the postgres cast operator `::`
```sql
select name::text from device where id=:id
```
This PR tries to handle the cast operator in the tokenizer. Let me know if this approach is ok and if you can think of more tests.

Use ':' (colon) for substitution and cast operator together

---

CHANGELOG.md
lib/src/types/text_codec.dart
pubspec.yaml
test/decode_test.dart
test/docker.dart

Attempt to add some missing comversions in PostgresTextDecoder.
Also corrected conversion for double & real.
Created after discussion about: [PostgresTextDecoder](https://github.com/isoos/postgresql-dart/issues/337)

Fixed double/real + added timestamp, numeric, date & json

---

CHANGELOG.md
lib/postgres.dart
lib/src/types/type_registry.dart

The is the first public-facing change for #346, enabling the customizable type converters to be added to a connection through the `TypeRegistry`.

Customizable type registry.

---

test/timeout_test.dart

Reproduction test for the two-transaction timeout issue.

---

CHANGELOG.md
lib/src/messages/logical_replication_messages.dart
pubspec.yaml
test/v3_logical_replication_test.dart

Reimplemented https://github.com/isoos/postgresql-dart/pull/343 for new codec API.

Support for binary pgoutput replication.

---

CHANGELOG.md
lib/messages.dart
lib/src/message_window.dart
lib/src/messages/logical_replication_messages.dart
lib/src/messages/server_messages.dart
lib/src/types/codec.dart
lib/src/types/type_registry.dart
lib/src/v3/connection.dart
lib/src/v3/protocol.dart
test/framer_test.dart

Reverts isoos/postgresql-dart#370

Revert "Asynchronous Codec methods + updated (deprecated) message processing."

---

CHANGELOG.md
lib/messages.dart
lib/src/message_window.dart
lib/src/messages/logical_replication_messages.dart
lib/src/messages/server_messages.dart
lib/src/types/codec.dart
lib/src/types/type_registry.dart
lib/src/v3/connection.dart
lib/src/v3/database_info.dart
lib/src/v3/protocol.dart
test/framer_test.dart

Reverts isoos/postgresql-dart#374

Revert "Revert "Asynchronous Codec methods + updated (deprecated) message processing.""

---

CHANGELOG.md
lib/postgres.dart
lib/src/pool/pool_impl.dart
lib/src/v3/connection.dart

Reverts #369 as we seem to have a path forward with cancellation requests.

Revert timeout notes and deprecations.

---

lib/src/v3/connection.dart

This addresses an issue I hit while running my server app in Docker (Swarm). Postgres was also running in the same swarm.
I was getting a "connection reset by peer" errors after a few minutes of idle operation, which seemed like were being handled by the library.
But trying to establish a new connection always resulted in a crash of my up with Unhandled exception saying "connection reset by peer" (again).
I tried to understand what's the best way to handle it inside the lib but it's still unclear to me where exactly it originates from.
The only thing that worked is adding `try-catch` in the `_close` method and silencing the error, which seems reasonable.
Note: The lib does throw `PgException` (which wraps the original `SocketError`) on a call to `execute` and I tried catching it, and …

Do not allow exceptions escape when closing broken connection

---

test/v3_test.dart

Here is a reproduction for the issue on #390 , hope that makes it easier to debug.

test for issue 390

---

lib/postgres.dart
lib/src/pool/pool_impl.dart
lib/src/v3/connection.dart
test/pool_test.dart
test/v3_close_test.dart

Lets users implement use cases such as #394 
Other alternative boolean names for the flag:
force
abortRunningQueries
abortRunning
cancelRunningQueries
cancelRunning

Flag in the close method to abort running queries

---

test/event_after_closing_test.dart

Test for issue#398

---

CHANGELOG.md
lib/src/v3/protocol.dart
test/event_after_closing_test.dart

Fix: multiple message processing overlap bug when SSL mode is 'disabled'.

---

CHANGELOG.md
lib/src/pool/pool_impl.dart
pubspec.yaml

@isoos There was a pending TODO from my force close implementation in the pool. I believe it's necessary. Otherwise the close call is not actually sent, right?
The tests in https://github.com/davidmartos96/demo_postgres_shelf are failing without these changes. To catch this in the tests I think we would need to run an empty transaction call, an let it open for a long time, with a Future.delayed and then check that the Postgres server has cleaned up the connection from pg_stat_activity.
Related to that, is the current `force close` implementation suppose to stop running queries like `pg_cancel_backend` or `pg_terminate_backend` do? Or does it just close the socket? It looks like with the current implementation, `pg_sleep` from the tests is not stopped, rather, no one is listening to the …

Don't ignore close in the pool when using force

---

CHANGELOG.md
lib/src/types/binary_codec.dart
pubspec.yaml
test/not_enough_bytes_test.dart

Fix: ARRAY_AGG (and other arrays) may return [null].

---

CHANGELOG.md
lib/src/pool/pool_impl.dart
lib/src/utils/package_pool_ext.dart
pubspec.yaml
test/utils/package_pool_ext_test.dart

Fix: Pool connection timeout implemented with Timer.

---

lib/postgres.dart
lib/src/exceptions.dart
test/error_handling_test.dart
test/transaction_test.dart

adds `DuplicateKeyException` and `ForeignKeyViolationException`

add DuplicateKeyException and ForeignKeyViolationException

---

CHANGELOG.md
lib/src/pool/pool_impl.dart

Recently, after updating to Dart 3.7 I started noticing the following error. I haven't been able to try lowering the Dart version, but I did try a possible patch in the library that makes it work. 
My understanding is that the pool is picking a connection that is closed or closing, so it will fail when trying to use it. I've tried deploying this fix in the server as it seemed low risk and I haven't seen the error since. 
Deployed postgres from pub again and they start showing up again.

Don't select closed/closing connections in the pool

---

CHANGELOG.md
lib/src/types/type_registry.dart

Fix read->real typo.
